### PR TITLE
run new console tests on CI

### PR DESCRIPTION
**Pull request by juliandescottes**

### CODE REVIEW

**Comment by juliandescottes** [comment]
Let's see if CI fails as expected here!

**Comment by nchevobbe** [comment]
> Let's see if CI fails as expected here!

It did :) 
```
1108 INFO TEST-UNEXPECTED-FAIL | devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_nodes_highlight.js | Test timed out - 
```

**Comment by nchevobbe** [comment]
We could also run ./mach eslint to make sure we won't have failure when landing the bundle ?

**Comment by tromey** [comment]
> We could also run ./mach eslint to make sure we won't have failure when landing the bundle ?

I don't think it makes sense to eslint a bundle in M-C, we should just add the bundles to the ignore file, if they aren't there already.

**Comment by nchevobbe** [comment]
there's some file that are not in the bundle, that we still copy from github to m-c (http://searchfox.org/mozilla-central/source/devtools/client/shared/components/reps).  I hope we will be able to remove `load-reps.js` at some point, but there would still be the tests. Do you think we should eslint-ignore them as well ?

**Comment by tromey** [comment]
> Do you think we should eslint-ignore them as well ?

I think a good general rule is to have eslint run at the canonical source for the code, and not anywhere downstream.  For bundles this makes sense because we don't control the code generated by any intermediate build step.  For tests I think it maybe still makes sense because eslint errors found in M-C aren't actionable there.  What do you think of this?

**Comment by juliandescottes** [comment]
I agree with @tromey, we should eslintignore in mozilla-central all the files which are being validated here in GitHub.

**Comment by nchevobbe** [comment]
okay, let's do this :)

**Pull request merged**
