### PR TITLE
release: bump version to v0.5.0

### PR DESCRIPTION
**Pull request by juliandescottes**
Bug : https://bugzilla.mozilla.org/show_bug.cgi?id=1351565
Try : https://treeherder.mozilla.org/#/jobs?repo=try&revision=978cee89746c7bc7057c7e5763a893d9b75c1281

### CODE REVIEW

**Comment by juliandescottes** [comment]
Thanks @nchevobbe 

We have failures on circle CI, not sure what this is about now...

**Comment by nchevobbe** [comment]
> We have failures on circle CI, not sure what this is about now...
I triggered a rebuild

**Comment by juliandescottes** [comment]
We already had the same 12 days ago: https://circleci.com/gh/devtools-html/reps/211?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by juliandescottes** [comment]
Looks like the debugger had a similar issue at some point https://github.com/devtools-html/debugger.html/pull/874

**Comment by juliandescottes** [comment]
CI and try are green :)

**Comment by nchevobbe** [comment]
:+1:

**Pull request merged**
